kind: pipeline
type: docker
name: linux-arm64

platform:
  arch: arm64
  os: linux

steps:
  - name: docker
    image: busybox
    commands:
      - ifconfig
  - name: docker
    image: plugins/docker
    settings:
      repo: x.x.x:x/koe:latest
      tags: latest
      registry: x.x.x:21212
      dockerfile: Dockerfile
      insecure: true
  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host:
        - x.x.x.x
      username: ubuntu
      password:
        from_secret: password
      port: 22
      command_timeout: 2m
      script:
        - ls
