[common]
port = 8080
DataDir = "/root/koe/config/data"

[sqlite]
filename = "koe.db"

[postgresql]
host = "postgres"
user = "postgres"
password = "postgres"
dbname = "koe"
port = "5432"
sslmode = "disable"
timezone = "Asia/Shanghai"